spring.application.name=authapi

spring.mongodb.uri=mongodb+srv://mahek080106_db_user:rWB4yAscqYgmFsdM@cluster0.kmd5hke.mongodb.net/auth_db?retryWrites=true&w=majority&appName=Cluster0

server.port=8080